### ISSUE TITLE
Fixing Login page UI

### ISSUE THREAD

**Issue by krishp007** [Lets-code-with-us/scamwebsiteV1#86] opened 2024-10-14 18:37 UTC
### ISSUE NAME

Login page UI

### ISSUE DESCRIPTION

First, there is no clear space or distinction between the login form and the news letter section on the login page. Also, the login form background should be black, consistent with the Home page background containing "Scam alert".

Please assign me this issue under hacktoberfest

Thank you

**Comment by Shu12388y** [comment] 2024-10-15 17:26
@krishp007 The issue is already raised

**Comment by Shu12388y** [comment] 2024-10-15 17:26
@krishp007 Close this issue

**Closed** 2024-10-15 18:05 UTC
